### ISSUE TITLE
graph mode doesn't seem to work

### ISSUE THREAD

**Issue by vicyao** [tansey/smoothfdr#1]
I'm trying to play around w/ the graph mode, but I wasn't able to get it to work, even on the example in README.

First, self.solver.set_data(y, edges, ntrails, trails, breakpoints, weights=weights) throws an error because pygfl trailsolver doesn't seem to take weights. 

Removing the weights argument, the code runs, but it seems like the code always runs into an issue ~line 294 in smoothed_fdr.py, where the division of weights is invalid (seems like either prior = 0 or 1) and all values become nan.

I'm wondering if there may be a different version of pygfl that's being used w/ this code?

**Comment by tansey** [comment]
I think you're right. I've got a few major updates I'm going to push in the next couple of weeks that should fix all of this, but for now it seems that the code is broken. I'm on it though!

**Comment by tansey** [comment]
Okay, a bit delayed, but the major overhaul is now pushed for both pygfl and smoothfdr. Can you try a fresh install of both and see if the new example works for you?

**Comment by tansey** [comment]
I'm going to go ahead and assume this is fixed and close out the issue.
